# Generated by Django 3.1.4 on 2020-12-21 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id_calendar', models.AutoField(primary_key=True, serialize=False)),
                ('name_calendar', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agenda',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id_day', models.AutoField(primary_key=True, serialize=False)),
                ('name_day', models.CharField(max_length=10, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dia',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DetailCalendar',
            fields=[
                ('id_detail_calendar', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendar_api.calendar')),
            ],
            options={
                'verbose_name': 'Detalle Agenda',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StateTurn',
            fields=[
                ('id_state_turn', models.AutoField(primary_key=True, serialize=False)),
                ('state_turn', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado Turno',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id_turn', models.AutoField(primary_key=True, serialize=False)),
                ('start_time_turn', models.TimeField()),
                ('end_time_turn', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('detail_calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendar_api.detailcalendar')),
                ('state_turn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendar_api.stateturn')),
            ],
            options={
                'verbose_name': 'Turno',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id_schedule', models.AutoField(primary_key=True, serialize=False)),
                ('start_time_schedule', models.TimeField()),
                ('end_time_schedule', models.TimeField()),
                ('interval_turn', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('up_date', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calendar_api.calendar')),
                ('days', models.ManyToManyField(to='calendar_api.Day')),
            ],
            options={
                'verbose_name': 'Horario',
                'ordering': ['-created'],
            },
        ),
    ]
