# Generated by Django 3.1.4 on 2020-12-12 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='calendar_api.schedule'),
        ),
    ]
